http:
  port: "8081"
  
accounts:
  host: "cxaccounts-api-guenther.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "cd96078435004936a3d2a5504f4d6b6b"
  client_secret: "D2a833de966f4182B56B62ED2f774acB"
  
accountsx:
  host: "diy-api-20201209.us-w2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "39100c46cff946b5868874321cb173c8"
  client_secret: "ff038c1977E04804aC16bbE0Af89cf12"
  user_id: "123"
  
transactions:
  wsdl: "http://apdev-accounts-ws.cloudhub.io/api/transactions?wsdl"
  service: "TransactionServiceService"
  port: "TransactionServicePort"
  address: "http://apdev-accounts-ws.cloudhub.io/api/transactions"